name = "Respeck"
author = "Rohan Verma"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f965b082246e5b6d985502ca1d6e5571f0333359c015c940bc5110079b81fabf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["1.21.1"]
