name = "Respeck"
author = "Rohan Verma"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7590bb41011ca33bba26433db2d6ed10206cdd4b698c80a1ab190b77d75e80ae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
