name = "Respeck"
author = "Rohan Verma"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b7c3b3463b32438910d368d2ec2fbe0f7269dfcc02b55e0ddcf8b3d4417a65f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["1.21.1"]
