name = "Respeck"
author = "Rohan Verma"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bbfef2b7484f0f60bb622fd9d2318fd6f83db46e4777c2837b02437cf788712"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
