name = "Respeck"
author = "Rohan Verma"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dfadc6e9e810e220bacc1d21d873c499c7cc70df4148e841ac54eb2245b2fe0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"

[options]
acceptable-game-versions = ["1.21.1"]
