version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
fastitemframes = true
farmersdelight = true
create_new_age = true
create_factory_logistics = true
lendersdelight = true
easymagic = true
etched = true
cataclysm = true
easyanvils = true
refurbished_furniture = true
copycats = true
automobility = true
herbsandharvest = true
diagonalwalls = true
createdieselgenerators = true
trinketsandbaubles = true
bellsandwhistles = true
amendments = true
handcrafted = true
moonlight = true
snowrealmagic = true
diagonalfences = true
advancednetherite = true
sophisticatedbackpacks = true
toms_peripherals = true
exposure = true
waterframes = true
enderscape = true
create_train_parts = true
merrymaking = true
cccbridge = true
supplementaries = true
create_vibrant_vaults = true
createbb = true
suppsquared = true
chipped = true
endrem = true
create = true
createcasing = true
yungscavebiomes = true
visualworkbench = true
createadditionallogistics = true
createmetalogistics = true
minecraft = true
create_dragons_plus = true
lootr = true
create_connected = true
createdeco = true
sophisticatedstorage = true
northstar = true
create_mobile_packages = true
beautify = true
diagonalwindows = true
create_bb = true
computercraft = true
createnuclear = true
pipeorgans = true
create_integrated_farming = true
